# Generated by Django 2.2.6 on 2019-10-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MomoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_number', models.CharField(editable=False, max_length=20)),
                ('amount', models.IntegerField()),
                ('payment_note', models.CharField(max_length=300, null=True)),
                ('request_status', models.CharField(max_length=70, null=True)),
                ('transaction_ref', models.TextField()),
                ('callback_id', models.TextField()),
            ],
        ),
    ]
